import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { LabelProvider } from "@/components/Context/Label";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'IPO',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LabelProvider>
          <Header />
          {children}
        </LabelProvider>
      </body>
    </html>
  );
}
